### ISSUE TITLE
Don't hardcode port number on the server

### ISSUE THREAD

**Issue by airnandez** [nicolaschotard/stackyter#1]
I suggest not to hardcode the port number on the server because this will create a conflict when two different users connect to the same host at CC:

https://github.com/nicolaschotard/stackyter/blob/325e8daa7f56af28f8e8a71f0e05b1dd21b36a31/stackyter.py#L79

To avoid conflicts, I would suggest that each individual use a different port number (server side), for instance 20000 + the user id (361 in my personal case). The port number to use serverside could be specified in the configuration file.

**Comment by nicolaschotard** [comment]
This has been fixed in commit e3ce5b7198dd466d7929de616c0cf5421b24b78c. A random port number (between 1025 and 65635 included) is now selected each time the script is run. This should allow to avoid any conflict is several users are connected at the same time.
