### ISSUE TITLE
Installation fails to pull pyaml from PyPI

### ISSUE THREAD

**Issue by HealthyPear** [nicolaschotard/stackyter#18]
I installed this project using pip within a very simple conda environment with just Python3 and pip.

The installation seems to be fine, but it fails to install the required `pyyaml` package.

Right now I don't know the cause of this issue, but from what I can see at least the way the installation code of this project is a bit old.

I suggest moving to [modern SetupTools](https://setuptools.pypa.io/en/latest/userguide/index.html) in particular configure your package with [pyproject.toml](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html) and set the script as an [entry point](https://setuptools.pypa.io/en/latest/userguide/entry_point.html).

If you want I can help with this with a PR.

**Comment by johannct** [comment]
a PR will be welcome, thanks!
