### ISSUE TITLE
Don't hardcode domain of Jupyter server

### ISSUE THREAD

**Issue by airnandez** [nicolaschotard/stackyter#2]
I suggest not to hardcode the full name of the target host in [this line](https://github.com/nicolaschotard/stackyter/blob/077d103773ce4f32497787a439171600279ccfef/stackyter.py#L89), because it may conflict with the definition of the same host in `$HOME/.ssh/config`. 

That is, don't assume the domain name is `in2p3.fr` but leave the `ssh` command resolve that according to its configuration file `$HOME/.ssh/config`. For instance, if my SSH configuration file contains:

```
Host cca7
   HostName cca7.in2p3.fr
   <other options>
```

`stackyter` won't work because the command issued is:

`ssh cca7.in2p3.fr`

which makes `ssh` to try to connect to `cca7.in2p3.fr.in2p3.fr` (note the double domain `in2p3.fr`) and there is no such host.

**Comment by nicolaschotard** [comment]
A new 'host' option has been implement in this commit da555fcee3b41a1812a518a94e0c410e40288ce0 to allow the user to choose the target host.
