### ISSUE TITLE
Use `Host` (or `Server` or `RemoteHost`) instead of `cca` for specifying Jupyter server in config file

### ISSUE THREAD

**Issue by airnandez** [nicolaschotard/stackyter#3]
I suggest to use `Host` or `Server` or `RemoteHost` (in the `stackyter` [configuration file](https://github.com/nicolaschotard/stackyter/blob/077d103773ce4f32497787a439171600279ccfef/example_config.yaml#L2)) to specify the name of the host where the Jupyter server runs, instead of `cca` which is IN2P3-specific and not very intuitive.

**Comment by nicolaschotard** [comment]
The new target 'host' option is now the default in the example config file (see this commit 4093c3c7cd3c4dc7e223af34b1540b31ca9ea01d)
