### ISSUE TITLE
Don't hardcode cipher algorithms for SSH connection to Jupyter server

### ISSUE THREAD

**Issue by airnandez** [nicolaschotard/stackyter#4]
I suggest not to hardcode the cipher algorithms (option `-c` of `ssh` command) to use for connecting to the Jupyter server in [this line](https://github.com/nicolaschotard/stackyter/blob/077d103773ce4f32497787a439171600279ccfef/stackyter.py#L89). I suggest to leave that configuration to the associated host entry in the SSH configuration file (i.e. `$HOME/.ssh.config`).

By the way, forcing to use an IPv4 address (option `-C4`) does not seem necessary here neither: that option, if desired, can be specified in the host entry in SSH configuration file.

**Comment by nicolaschotard** [comment]
Do you have a suggestion on how to handle the different set of options for `ssh`, and specifically for the ones that could be optional (against those which that should not be optional)?

**Comment by airnandez** [comment]
I would say that the `ssh` command should be something simple such as:

`ssh -X -Y -tt -L 20001:localhost:<remote port> <user>@<hostname>`

If `<user>` is not specified in the `stackyter` configuration file, leave it empty in the `ssh` command (and remove `@`): the user is either specified in `~/.ssh/config` and SSH will know how to establish the connection, or is not specified at all and SSH will assume it is the same user name of the client host.

I'm not sure the the options `-X` (enable X11 forwarding) and `-Y` (enable trusted X11 forwarding)  are strictly necessary, unless within a notebook you launch an instance of DS9 which needs X11.

**Comment by nicolaschotard** [comment]
Ok, I agree that this should be as general as possible. I will make the necessary changes for the `ssh` connection. For the `-X` and `-Y` option, I will leave them for now so we can automatically use DS9 or any other instance that needs X11.

**Comment by nicolaschotard** [comment]
New `--sshopts` in commit a2f596a41e717c25e28fbf3ac80e29230df77865 + no mandatory user name needed anymore.

**Comment by nicolaschotard** [comment]
Actually removed this option (and the cca one) to simplify the ssh connection. See commit https://github.com/nicolaschotard/stackyter/issues
