### ISSUE TITLE
Use default configuration file

### ISSUE THREAD

**Issue by airnandez** [nicolaschotard/stackyter#5]
It would be useful if `stackyter` could look for a default configuration file (e.g. `$HOME/.stackyter.conf`) so that one can invoke the command without specifying the configuration file every time:

```
stackyter.py
```

However, the option `--config` must be kept to be able to use different configuration files, if needed.

**Comment by nicolaschotard** [comment]
Done in commit c9a39fb8159d22b752d5cd32a0b1e6052fbffa90
